PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/codekill_deb.mk \
    $(LOCAL_DIR)/codekill_d2att.mk \
    $(LOCAL_DIR)/codekill_d2spr.mk \
    $(LOCAL_DIR)/codekill_d2tmo.mk \
    $(LOCAL_DIR)/codekill_d2vzw.mk \
    $(LOCAL_DIR)/codekill_e975.mk \
    $(LOCAL_DIR)/codekill_e980.mk \
    $(LOCAL_DIR)/codekill_endeavoru.mk \
    $(LOCAL_DIR)/codekill_flo.mk \
    $(LOCAL_DIR)/codekill_grouper.mk \
    $(LOCAL_DIR)/codekill_hercules.mk \
    $(LOCAL_DIR)/codekill_i605.mk \
    $(LOCAL_DIR)/codekill_i9300.mk \
    $(LOCAL_DIR)/codekill_i9305.mk \
    $(LOCAL_DIR)/codekill_jewel.mk \
    $(LOCAL_DIR)/codekill_m7att.mk \
    $(LOCAL_DIR)/codekill_m7spr.mk \
    $(LOCAL_DIR)/codekill_m7tmo.mk \
    $(LOCAL_DIR)/codekill_m7ul.mk \
    $(LOCAL_DIR)/codekill_m7vzw.mk \
    $(LOCAL_DIR)/codekill_manta.mk \
    $(LOCAL_DIR)/codekill_maguro.mk \
    $(LOCAL_DIR)/codekill_mako.mk \
    $(LOCAL_DIR)/codekill_maserati.mk \
    $(LOCAL_DIR)/codekill_ovation.mk \
    $(LOCAL_DIR)/codekill_p880.mk \
    $(LOCAL_DIR)/codekill_pollux.mk \
    $(LOCAL_DIR)/codekill_jfltevzw.mk \
    $(LOCAL_DIR)/codekill_jflteatt.mk \
    $(LOCAL_DIR)/codekill_jfltecan.mk \
    $(LOCAL_DIR)/codekill_jfltecri.mk \
    $(LOCAL_DIR)/codekill_jfltespr.mk \
    $(LOCAL_DIR)/codekill_jfltetmo.mk \
    $(LOCAL_DIR)/codekill_t0lteatt.mk \
    $(LOCAL_DIR)/codekill_t0ltetmo.mk \
    $(LOCAL_DIR)/codekill_toro.mk \
    $(LOCAL_DIR)/codekill_toroplus.mk \
    $(LOCAL_DIR)/codekill_p700.mk \
    $(LOCAL_DIR)/codekill_tilapia.mk \
    $(LOCAL_DIR)/codekill_yuga.mk \
    $(LOCAL_DIR)/codekill_vigor.mk
